[tool.black]
line_length = 100
target_version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.git
    | \.venv
    | \.pytest_cache
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py
)
'''